parameters:
  kapitan:
    compile:
      - input_paths:
          - traefik/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - traefik/component/main.jsonnet
        input_type: jsonnet
        output_path: traefik/
