parameters:
  kapitan:
    dependencies:
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/ingressroute.yaml
        output_path: dependencies/traefik/manifests/crds/ingressroute-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/ingressroutetcp.yaml
        output_path: dependencies/traefik/manifests/crds/ingressroutetcp-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/ingressrouteudp.yaml
        output_path: dependencies/traefik/manifests/crds/ingressrouteudp-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/middlewares.yaml
        output_path: dependencies/traefik/manifests/crds/middlewares-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/tlsoptions.yaml
        output_path: dependencies/traefik/manifests/crds/tlsoptions-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/tlsstores.yaml
        output_path: dependencies/traefik/manifests/crds/tlsstores-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/traefikservices.yaml
        output_path: dependencies/traefik/manifests/crds/traefikservices-crd.yaml
      - type: https
        source: https://raw.githubusercontent.com/traefik/traefik-helm-chart/master/traefik/crds/serverstransports.yaml
        output_path: dependencies/traefik/manifests/crds/serverstransports-crd.yaml
      - type: helm
        output_path: dependencies/traefik/helmcharts/traefik
        source: https://helm.traefik.io/traefik
        version: ${traefik:charts:traefik}
        chart_name: traefik
    compile:
      - input_paths:
          - traefik/component/app.jsonnet
        input_type: jsonnet
        output_path: apps/
      - input_paths:
          - traefik/component/main.jsonnet
        input_type: jsonnet
        output_path: traefik/
      - output_path: traefik/10_traefik_helmchart
        input_type: helm
        output_type: yaml
        input_paths:
          - traefik/helmcharts/traefik
        helm_values: ${traefik:helmValues}
        helm_params:
          release_name: traefik
          namespace: '${traefik:namespace}'
      - output_path: traefik/00_crds/
        input_type: copy
        input_paths:
          - traefik/manifests/crds/
